### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by zanbaldwin** [phpmentoring/testapp#58]
I'm putting forward a suggestion to use a [Gitter](https://gitter.im) chatroom for PHP Mentoring.

It's brilliant that there are over a hundred people on the IRC channel (126 as I'm writing this) but unfortunately it's not the easiest procotol to grasp, especially for beginners to PHP and programming (which is the whole purpose of this project).
While I support [some projects not using Gitter](https://github.com/symfony/symfony/issues/12885#issuecomment-65935540), I feel that the low barrier-of-entry that Gitter provides is a perfect addition (not replacement) for PHP Mentoring.

Providing a link to a chatroom where they can login with their GitHub accounts (the same login process that the PHP Mentoring webapp already uses) is, IMO, way easier than saying _join `#phpmentoring` on `irc.freenode.net`_.

Obviously we shouldn't use a public chatroom for actually mentoring, that would be chaos! Kind of like a client changing specifications halfway through a project - we don't want to scare apprentices off too quickly.
It's great that we have one-to-one interactions with the people we are mentoring, but we do need a more social community - apprentices discussing ideas with other apprentices, and mentors discussing teaching methods with other mentors (read: first time mentoring, no idea if I'm doing it right).

If anyone does approve this suggestion, perhaps it would be a good idea to create a new repository (`phpmentoring/chat` maybe) since Gitter ties chatrooms with repositories. That repository could have a nice little README about the chatroom.

**Comment by dragonmantank** [comment]
Personally from me, this is a -1. 

Currently the IRC channel does facilitate apprentice-apprentice / mentor-mentor / mentor-apprentice discussion and help, as well as a safe social area on IRC, and has done so since the project started. 

While I'm not against services such as Gitter or Slack or whatever in practice, it does cause a fragmentation of the community when there doesn't need to be one. The IRC channel is also not a requirement so mentors and apprentices can talk via e-mail or any other means. IRC is just a traditional way of providing a social space.

We do offer a link to the web interface for Freenode, in which the only barrier of entry is typing in a username and joining. `#phpmentoring` is an unauthenticated channel so anyone can get online. Clients have also come a long way and take only a few moments to set up. There are online ones like IRCCloud that also provide a great mobile app experience.

Having it on IRC also fosters the idea that, if you need other help, you can easily swap to a different room on Freenode for help (`##php` for help, or '#phpc` if you decide you want more social stuff, or any myriad of rooms for projects you might be working with). Many opens source projects use IRC as their support base, so learning IRC will only help devs. 

So while I appreciate the request for a Gitter room, again, I'd have to -1 this. 

I'll leave this open for any more comments though.

**Comment by dragonmantank** [comment]
Been a while, so closing this.

**Comment by auroraeosrose** [comment]
The other reason to prefer irc is we already have a mechanism in place for moderation and a set of people who take care of the irc channel - yet another communication mechanism would necessitate yet another team of users and we are already short on help for the project itself (infrastructure, the app, etc)
